name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: '1.26'
            - run: go vet ./...
            - uses: golangci/golangci-lint-action@v6
              with:
                version: v.2.12.2
            - run: go test ./...
            - run: go build .